import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Nav/Navbar";
import ThemeProviders from "@/app/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProviders>
        <body
          className={`bg-gradient-to-r dark:from-gray-900 from-gray-400 dark:via-zinc-900 via-zinc-300 dark:to-stone-800 to-stone-400`}
        >
          <Navbar />
          {children}
        </body>
      </ThemeProviders>
    </html>
  );
}
